backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "landing"
    label: "Landing Page"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Things to Do", name: "things", widget: "list" }